name: kelola_barang
description: "Sahabat Pengelolaan inventarismu."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_contact_picker: ^0.0.10
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^4.0.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  ionicons: ^0.2.2
  logger: ^2.5.0
  mobile_scanner: ^6.0.7
  pdf: ^3.11.3
  printing: ^5.14.2
  pull_to_refresh_flutter3: ^2.0.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
